"""Domain models — typed representations of bots, messages and PRDs.

We use pydantic for automatic validation and bidirectional JSON
serialization to/from Firestore. Models are immutable
(``model_config frozen=True``) where it makes sense, to avoid
accidental mutations after persistence.
"""

from __future__ import annotations

import hashlib
import secrets
from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


def _now_utc() -> datetime:
    return datetime.now(UTC)


def compute_token_hash(token: str) -> str:
    """Compute a stable, non-reversible hash of the bot token.

    Used as path segment in webhook URLs so that the URL does not expose
    the token. Takes the first 16 hex chars of SHA-256 (64 bit), enough
    to avoid collisions in a registry of up to ~1000 bots.

    Args:
        token: Telegram bot token.

    Returns:
        16-character hex string.
    """
    return hashlib.sha256(token.encode("utf-8")).hexdigest()[:16]


def generate_webhook_secret() -> str:
    """Generate a random URL-safe secret token (32 bytes)."""
    return secrets.token_urlsafe(32)


class BotConfig(BaseModel):
    """Configuration of a registered child bot.

    Maps to the Firestore document ``bots/{chat_id}``.
    """

    model_config = ConfigDict(frozen=False)

    token: str = Field(..., description="Telegram bot token.", repr=False)
    token_hash: str = Field(..., description="SHA-256[:16] of the token.")
    chat_id: int = Field(..., description="Monitored Telegram group ID.")
    chat_title: str = Field(default="", description="Group title (cached).")
    n: int = Field(..., ge=1, le=500, description="Max messages per batch.")
    last_read_message_id: int = Field(
        default=0, description="ID of the last already-processed message."
    )
    last_message_ts: datetime | None = Field(
        default=None, description="Timestamp of the last received message."
    )
    has_pending: bool = Field(
        default=False,
        description="True if there are buffered messages to process.",
    )
    webhook_secret: str = Field(
        default_factory=generate_webhook_secret,
        repr=False,
        description="Secret token sent by Telegram in the webhook header.",
    )
    enabled: bool = Field(default=True)
    created_at: datetime = Field(default_factory=_now_utc)

    def redacted_token(self) -> str:
        """Safe token representation for logs (first 8 hash chars)."""
        return f"tok:{self.token_hash[:8]}…"

    def to_firestore(self) -> dict[str, Any]:
        """Serialization compatible with Firestore (native datetimes)."""
        return self.model_dump(mode="python")

    @classmethod
    def from_firestore(cls, data: dict[str, Any]) -> BotConfig:
        """Deserialization from Firestore document."""
        return cls.model_validate(data)


class BufferedMessage(BaseModel):
    """A message awaiting processing.

    Maps to the Firestore document
    ``bots/{chat_id}/buffer/{message_id}``.
    """

    model_config = ConfigDict(frozen=True)

    message_id: int = Field(..., ge=1)
    chat_id: int
    user_id: int | None = None
    user_name: str = Field(default="Sconosciuto")
    text: str
    ts: datetime

    def to_firestore(self) -> dict[str, Any]:
        return self.model_dump(mode="python")

    @classmethod
    def from_firestore(cls, data: dict[str, Any]) -> BufferedMessage:
        return cls.model_validate(data)


class ClassifyResult(BaseModel):
    """Output of ``llm.classify_batch``."""

    model_config = ConfigDict(frozen=True)

    needs_prd: bool
    reason: str = ""


class PRDDoc(BaseModel):
    """A single PRD generated by the LLM, ready to be sent.

    ``trigger_message_id`` points to the batch message that triggered
    this PRD; from it we derive ``trigger_user`` and ``trigger_ts``.
    """

    model_config = ConfigDict(frozen=True)

    title: str
    markdown: str
    trigger_message_id: int | None = None
    trigger_user: str = "Sconosciuto"
    trigger_ts: datetime | None = None

    def filename(self) -> str:
        """Suggested filename when sending as Telegram document."""
        slug = "".join(c if c.isalnum() or c in "-_ " else "_" for c in self.title)
        slug = "_".join(slug.split())[:60] or "PRD"
        return f"PRD_{slug}.md"
